<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = '阿富汗'; // Afghanistan
$_country_lang["2"] = '阿爾巴尼亞'; // Albania
$_country_lang["3"] = '阿爾及利亞'; // Algeria
$_country_lang["4"] = '美屬薩摩亞'; // American Samoa
$_country_lang["5"] = '安道爾'; // Andorra
$_country_lang["6"] = '安哥拉'; // Angola
$_country_lang["7"] = '英屬安圭拉'; // Anguilla
$_country_lang["8"] = '南極洲'; // Antarctica
$_country_lang["9"] = '安地卡及巴布達'; // Antigua and Barbuda
$_country_lang["10"] = '阿根廷'; // Argentina
$_country_lang["11"] = '亞美尼亞'; // Armenia
$_country_lang["12"] = '阿魯巴'; // Aruba
$_country_lang["13"] = '澳洲'; // Australia
$_country_lang["14"] = '奧地利'; // Austria
$_country_lang["15"] = '亞塞拜然'; // Azerbaijan
$_country_lang["16"] = '巴哈馬'; // Bahamas
$_country_lang["17"] = '巴林'; // Bahrain
$_country_lang["18"] = '孟加拉'; // Bangladesh
$_country_lang["19"] = '巴貝多'; // Barbados
$_country_lang["20"] = '白俄羅斯'; // Belarus
$_country_lang["21"] = '比利時'; // Belgium
$_country_lang["22"] = '貝里斯'; // Belize
$_country_lang["23"] = '貝南'; // Benin
$_country_lang["24"] = '百慕達'; // Bermuda
$_country_lang["25"] = '不丹'; // Bhutan
$_country_lang["26"] = '玻利維亞'; // Bolivia
$_country_lang["27"] = '波赫'; // Bosnia and Herzegowina
$_country_lang["28"] = '波札那'; // Botswana
$_country_lang["29"] = '布威島'; // Bouvet Island
$_country_lang["30"] = '巴西'; // Brazil
$_country_lang["31"] = '英屬印度洋地區'; // British Indian Ocean Territory
$_country_lang["32"] = '汶萊達魯薩蘭'; // Brunei Darussalam
$_country_lang["33"] = '保加利亞'; // Bulgaria
$_country_lang["34"] = '布吉納法索'; // Burkina Faso
$_country_lang["35"] = '汶萊'; // Burundi
$_country_lang["36"] = '柬埔寨'; // Cambodia
$_country_lang["37"] = '喀麥隆'; // Cameroon
$_country_lang["38"] = '加拿大'; // Canada
$_country_lang["39"] = '維德角'; // Cape Verde
$_country_lang["40"] = '開曼群島'; // Cayman Islands
$_country_lang["41"] = '中非'; // Central African Republic
$_country_lang["42"] = '查德'; // Chad
$_country_lang["43"] = '智利'; // Chile
$_country_lang["44"] = '中華人民共和國'; // China
$_country_lang["45"] = '聖誕島'; // Christmas Island
$_country_lang["46"] = '可可斯群島'; // Cocos (Keeling) Islands
$_country_lang["47"] = '哥倫比亞'; // Colombia
$_country_lang["48"] = '葛摩'; // Comoros
$_country_lang["49"] = '民主剛果'; // Congo
$_country_lang["50"] = '庫克群島'; // Cook Islands
$_country_lang["51"] = '哥斯大黎加'; // Costa Rica
$_country_lang["52"] = '象牙海岸'; // Cote D&#39;Ivoire
$_country_lang["53"] = '克羅埃西亞'; // Croatia
$_country_lang["54"] = '古巴'; // Cuba
$_country_lang["55"] = '塞普勒斯'; // Cyprus
$_country_lang["56"] = '捷克'; // Czech Republic
$_country_lang["57"] = '丹麥'; // Denmark
$_country_lang["58"] = '吉布地'; // Djibouti
$_country_lang["59"] = '多米尼克'; // Dominica
$_country_lang["60"] = '多明尼加'; // Dominican Republic
$_country_lang["61"] = '東帝汶'; // East Timor
$_country_lang["62"] = '厄瓜多'; // Ecuador
$_country_lang["63"] = '埃及'; // Egypt
$_country_lang["64"] = '薩爾瓦多'; // El Salvador
$_country_lang["65"] = '赤道幾內亞'; // Equatorial Guinea
$_country_lang["66"] = '厄立垂亞'; // Eritrea
$_country_lang["67"] = '愛沙尼亞'; // Estonia
$_country_lang["68"] = '衣索匹亞'; // Ethiopia
$_country_lang["69"] = '福克蘭群島'; // Falkland Islands (Malvinas)
$_country_lang["70"] = '法羅群島'; // Faroe Islands
$_country_lang["71"] = '斐濟'; // Fiji
$_country_lang["72"] = '芬蘭'; // Finland
$_country_lang["73"] = '法國'; // France
$_country_lang["74"] = '法屬美特羅波利坦'; // France, Metropolitan
$_country_lang["75"] = '法屬圭亞那'; // French Guiana
$_country_lang["76"] = '法屬波利尼西亞'; // French Polynesia
$_country_lang["77"] = '法屬南方及南極陸地'; // French Southern Territories
$_country_lang["78"] = '加彭'; // Gabon
$_country_lang["79"] = '甘比亞'; // Gambia
$_country_lang["80"] = '喬治亞'; // Georgia
$_country_lang["81"] = '德國'; // Germany
$_country_lang["82"] = '迦納'; // Ghana
$_country_lang["83"] = '直布羅陀'; // Gibraltar
$_country_lang["84"] = '希臘'; // Greece
$_country_lang["85"] = '格陵蘭'; // Greenland
$_country_lang["86"] = '格瑞那達'; // Grenada
$_country_lang["87"] = '瓜德魯普島'; // Guadeloupe
$_country_lang["88"] = '關島'; // Guam
$_country_lang["89"] = '瓜地馬拉'; // Guatemala
$_country_lang["90"] = '幾內亞'; // Guinea
$_country_lang["91"] = '幾內亞比索'; // Guinea-bissau
$_country_lang["92"] = '蓋亞那'; // Guyana
$_country_lang["93"] = '海地'; // Haiti
$_country_lang["94"] = '赫德及麥當勞群島'; // Heard and Mc Donald Islands
$_country_lang["95"] = '宏都拉斯'; // Honduras
$_country_lang["96"] = '香港'; // Hong Kong
$_country_lang["97"] = '匈牙利'; // Hungary
$_country_lang["98"] = '冰島'; // Iceland
$_country_lang["99"] = '印度'; // India
$_country_lang["100"] = '印尼'; // Indonesia
$_country_lang["101"] = '伊朗'; // Iran (Islamic Republic of)
$_country_lang["102"] = '伊拉克'; // Iraq
$_country_lang["103"] = '愛爾蘭'; // Ireland
$_country_lang["104"] = '以色列'; // Israel
$_country_lang["105"] = '義大利'; // Italy
$_country_lang["106"] = '牙買加'; // Jamaica
$_country_lang["107"] = '日本'; // Japan
$_country_lang["108"] = '約旦'; // Jordan
$_country_lang["109"] = '哈薩克'; // Kazakhstan
$_country_lang["110"] = '肯亞'; // Kenya
$_country_lang["111"] = '吉里巴斯'; // Kiribati
$_country_lang["112"] = '北韓'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = '南韓'; // Korea, Republic of
$_country_lang["114"] = '科威特'; // Kuwait
$_country_lang["115"] = '吉爾吉斯'; // Kyrgyzstan
$_country_lang["116"] = '寮國'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = '拉脫維亞'; // Latvia
$_country_lang["118"] = '黎巴嫩'; // Lebanon
$_country_lang["119"] = '賴索托'; // Lesotho
$_country_lang["120"] = '賴比瑞亞'; // Liberia
$_country_lang["121"] = '利比亞'; // Libyan Arab Jamahiriya
$_country_lang["122"] = '列支敦斯登'; // Liechtenstein
$_country_lang["123"] = '立陶宛'; // Lithuania
$_country_lang["124"] = '盧森堡'; // Luxembourg
$_country_lang["125"] = '澳門'; // Macau
$_country_lang["126"] = '馬其頓, The Former Yugoslav Republic of'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = '馬達加斯加'; // Madagascar
$_country_lang["128"] = '馬拉威'; // Malawi
$_country_lang["129"] = '馬來西亞'; // Malaysia
$_country_lang["130"] = '馬爾地夫'; // Maldives
$_country_lang["131"] = '馬利'; // Mali
$_country_lang["132"] = '馬耳他'; // Malta
$_country_lang["133"] = '馬紹爾群島'; // Marshall Islands
$_country_lang["134"] = '法屬馬丁尼克'; // Martinique
$_country_lang["135"] = '茅利塔尼亞'; // Mauritania
$_country_lang["136"] = '模里西斯'; // Mauritius
$_country_lang["137"] = '美亞特'; // Mayotte
$_country_lang["138"] = '墨西哥'; // Mexico
$_country_lang["139"] = '密克羅尼西亞聯邦'; // Micronesia, Federated States of
$_country_lang["140"] = '摩爾多瓦'; // Moldova, Republic of
$_country_lang["141"] = '摩納哥'; // Monaco
$_country_lang["142"] = '蒙古'; // Mongolia
$_country_lang["241"] = '蒙特內哥羅'; //Montenegro
$_country_lang["143"] = '蒙塞拉特島'; // Montserrat
$_country_lang["144"] = '摩洛哥'; // Morocco
$_country_lang["145"] = '莫三比克'; // Mozambique
$_country_lang["146"] = '緬甸'; // Myanmar
$_country_lang["147"] = '奈米比亞'; // Namibia
$_country_lang["148"] = '諾魯'; // Nauru
$_country_lang["149"] = '尼泊爾'; // Nepal
$_country_lang["150"] = '荷蘭'; // Netherlands
$_country_lang["151"] = '荷屬安地列斯群島'; // Netherlands Antilles
$_country_lang["152"] = '新喀里多尼亞島'; // New Caledonia
$_country_lang["153"] = '紐西蘭'; // New Zealand
$_country_lang["154"] = '尼加拉瓜'; // Nicaragua
$_country_lang["155"] = '尼日'; // Niger
$_country_lang["156"] = '奈及利亞'; // Nigeria
$_country_lang["157"] = '紐埃'; // Niue
$_country_lang["158"] = '諾福克島'; // Norfolk Island
$_country_lang["159"] = '北馬里亞納群島'; // Northern Mariana Islands
$_country_lang["160"] = '挪威'; // Norway
$_country_lang["161"] = '阿曼'; // Oman
$_country_lang["162"] = '巴基斯坦'; // Pakistan
$_country_lang["163"] = '帛琉'; // Palau
$_country_lang["164"] = '巴拿馬'; // Panama
$_country_lang["165"] = '巴布亞新幾內亞'; // Papua New Guinea
$_country_lang["166"] = '巴拉圭'; // Paraguay
$_country_lang["167"] = '秘魯'; // Peru
$_country_lang["168"] = '菲律賓'; // Philippines
$_country_lang["169"] = '皮特康島'; // Pitcairn
$_country_lang["170"] = '波蘭'; // Poland
$_country_lang["171"] = '葡萄牙'; // Portugal
$_country_lang["172"] = '波多黎各'; // Puerto Rico
$_country_lang["173"] = '卡達'; // Qatar
$_country_lang["174"] = '留尼旺'; // Reunion
$_country_lang["175"] = '羅馬尼亞'; // Romania
$_country_lang["176"] = '俄羅斯'; // Russian Federation
$_country_lang["177"] = '盧安達'; // Rwanda
$_country_lang["178"] = '聖克里斯多福與尼維斯'; // Saint Kitts and Nevis
$_country_lang["179"] = '聖露西亞'; // Saint Lucia
$_country_lang["180"] = '聖文森及格瑞那丁'; // Saint Vincent and the Grenadines
$_country_lang["181"] = '薩摩亞'; // Samoa
$_country_lang["182"] = '聖馬利諾'; // San Marino
$_country_lang["183"] = '聖多美普林西比'; // Sao Tome and Principe
$_country_lang["184"] = '沙烏地阿拉伯王國'; // Saudi Arabia
$_country_lang["185"] = '塞內加爾'; // Senegal
$_country_lang["240"] = '塞爾維亞共和國'; //Serbia
$_country_lang["186"] = '塞席爾'; // Seychelles
$_country_lang["187"] = '獅子山'; // Sierra Leone
$_country_lang["188"] = '新加坡'; // Singapore
$_country_lang["189"] = '斯洛伐克'; // Slovakia (Slovak Republic)
$_country_lang["190"] = '斯洛維尼亞'; // Slovenia
$_country_lang["191"] = '索羅門群島'; // Solomon Islands
$_country_lang["192"] = '索馬利亞'; // Somalia
$_country_lang["193"] = '南非'; // South Africa
$_country_lang["194"] = '南喬治亞及南三明治群島 '; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = '西班牙'; // Spain
$_country_lang["196"] = '斯里蘭卡'; // Sri Lanka
$_country_lang["197"] = '聖海蓮娜'; // St. Helena
$_country_lang["198"] = '聖皮埃與密克隆群島'; // St. Pierre and Miquelon
$_country_lang["199"] = '蘇丹'; // Sudan
$_country_lang["200"] = '蘇利南'; // Suriname
$_country_lang["201"] = '冷岸和央麥恩島'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = '史瓦濟蘭'; // Swaziland
$_country_lang["203"] = '瑞典'; // Sweden
$_country_lang["204"] = '瑞士'; // Switzerland
$_country_lang["205"] = '敘利亞'; // Syrian Arab Republic
$_country_lang["206"] = '台灣'; // Taiwan
$_country_lang["207"] = '塔吉克'; // Tajikistan
$_country_lang["208"] = '坦尚尼亞'; // Tanzania, United Republic of
$_country_lang["209"] = '泰國'; // Thailand
$_country_lang["210"] = '多哥'; // Togo
$_country_lang["211"] = '托克勞'; // Tokelau
$_country_lang["212"] = '東加王國'; // Tonga
$_country_lang["213"] = '千里達及托巴哥'; // Trinidad and Tobago
$_country_lang["214"] = '突尼西亞'; // Tunisia
$_country_lang["215"] = '土耳其'; // Turkey
$_country_lang["216"] = '土庫曼'; // Turkmenistan
$_country_lang["217"] = '英屬土克凱可群島'; // Turks and Caicos Islands
$_country_lang["218"] = '吐瓦魯'; // Tuvalu
$_country_lang["219"] = '烏干達'; // Uganda
$_country_lang["220"] = '烏克蘭'; // Ukraine
$_country_lang["221"] = '阿拉伯聯合大公國'; // United Arab Emirates
$_country_lang["222"] = '英國'; // United Kingdom
$_country_lang["223"] = '美國'; // United States
$_country_lang["224"] = '美國本土外小島嶼'; // United States Minor Outlying Islands
$_country_lang["225"] = '烏拉圭'; // Uruguay
$_country_lang["226"] = '烏茲別克'; // Uzbekistan
$_country_lang["227"] = '萬那杜'; // Vanuatu
$_country_lang["228"] = '梵蒂岡'; // Vatican City State (Holy See)
$_country_lang["229"] = '委內瑞拉'; // Venezuela
$_country_lang["230"] = '越南'; // Viet Nam
$_country_lang["231"] = '英屬維京群島'; // Virgin Islands (British)
$_country_lang["232"] = '美屬維京群島'; // Virgin Islands (U.S.)
$_country_lang["233"] = '沃利斯和富圖納群島'; // Wallis and Futuna Islands
$_country_lang["234"] = '西撒哈拉'; // Western Sahara
$_country_lang["235"] = '葉門'; // Yemen
$_country_lang["236"] = '塞爾維亞與蒙特內哥羅'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = '剛果民主共和國'; // Congo, Democratic Republic of the
$_country_lang["238"] = '尚比亞'; // Zambia
$_country_lang["239"] = '辛巴威'; // Zimbabwe
?>